import Document,{ Html, Head, Main, NextScript } from 'next/document'
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default class MyDocument extends Document {
  
  render() {

    return (
      <Html lang="en">
        <Head />
        <body className='' dir='rtl'>
            <Main />
            <NextScript />
        </body>
      </Html>
    )
  }
}